path:
  file: "./outout_GRID" 
  ckpt_path: "ckpt/MovieAnimation"
  log_path: "log/MovieAnimation"
  result_path: "result/MovieAnimation"
  model_config: "model_config/MovieAnimation"
optimizer:
  batch_size: 64
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
  init_lr: 0.00625
step:
  total_step: 1000000
  log_step: 100
  synth_step: 50
  val_step: 50
  save_step: 
dataset:
  shuffle_refmel: True
